- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: Tower
    instance_type: t2.micro
    security_group: sg-6c37a60b
    image: ami-2cade64c
    region: us-west-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group_id: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-cfa6d3ab
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.private_ip }}"
        port: 22
        delay: 60
        sleep: 5
        timeout: 500
        search_regex=OpenSSH
        state: started
      with_items: "{{ ec2.instances }}"
      
- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  roles:
    - apache_role


- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'    
