---
 name: Terminate EC2 Apache Instance
  hosts: tag_role_apache
  connection: local
  gather_facts: false
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        region: us-west-1
        instance_id: "{{ item }}"
      with_items: hostvars[inventory_hostname]['ensible_ec2_instance_id']    
